export const environment = {
  endPoint: 'https://logto.gugloplex.com/oidc',
  appId: 'ppdegn5tphxsk7nj4f66q',
  resource: 'https://gugloplex.com/api',
  resourceScope: 'access:resource',
  origin: 'http://localhost:8080',
  apiTarget: 'https://tsp.gugloplex.com',
  baseUrl: 'http://localhost:3000',
  firebaseOptions: {
    projectId: 'travel-saas-platform-prod',
    appId: '1:535055410790:web:2890c1ebae5327cd9c6fa7',
    storageBucket: 'travel-saas-platform-prod.firebasestorage.app',
    apiKey: 'AIzaSyANPUdnnqJ6MKsg5lTlxFtStkNMXK8exwE',
    authDomain: 'travel-saas-platform-prod.firebaseapp.com',
    messagingSenderId: '535055410790',
    measurementId: 'G-B1WXCRF3KF',
    projectNumber: '535055410790',
    version: '2',
  },
  reCaptchaKey: '6LflK38sAAAAAErZK0s3GRQzyW7vhk7HEziPLhAH',
} as const;
